#!/bin/sh

# Wait for the property system to be up.
while [ ! -e /dev/socket/property_service ]; do sleep 0.1; done

# Init wlan interface on boot
while [ ! -e /dev/wlan ]; do sleep 0.2; done
echo 1 > /dev/ipa && echo ON > /dev/wlan

#screen brightness slider
mount -o bind /sys/class/backlight/panel0-backlight/ /sys/class/backlight/backlight
chmod 0666 /sys/class/backlight/panel0-backlight/brightness
chmod 0666 /sys/class/backlight/backlight/

#wireless display
setprop ubuntu.widi.supported 1

# Set schedtune boost
echo 20 > /sys/fs/cgroup/schedtune/schedtune.boost
echo 1 > /sys/fs/cgroup/schedtune/schedtune.prefer_idle

#apt
sudo mount --bind /home/phablet/aptcache /var/cache/apt
